[package]
name = "trans-misja"
version = "0.1.0"
edition = "2021"

[dependencies]
gio = "0.20.7"
glib-macros = "0.20.7"
gtk4 = "0.9.5"
hound = "3.5.1"
image = "0.25.5"
rayon = "1.10.0"
tract-onnx = "0.21.8"
